steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/wp-repo/wordpress:$SHORT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/wp-repo/wordpress:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/wordpress'
      - 'wordpress=us-central1-docker.pkg.dev/$PROJECT_ID/wp-repo/wordpress:$SHORT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=wp-cluster'

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'rollout'
      - 'status'
      - 'deployment/wordpress'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=wp-cluster'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/wp-repo/wordpress:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
